name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: "https://registry.npmjs.org"
      - name: Config Github Account
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "pengfeizhou@foxmail.com"
          git config user.name "pengfei.zhou"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout main
      - name: Echo current Version
        run: |
          echo ${GITHUB_REF:11}>version
          echo "Current Version is "${GITHUB_REF:11}
      - name: Publish
        run: |
          sh publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
